FROM gradle:9.3.1-jdk25
WORKDIR /workspace
COPY settings.gradle.kts build.gradle.kts gradle.lockfile ./
COPY config ./config
COPY src ./src
RUN --mount=type=cache,target=/home/gradle/.gradle gradle --init-script config/gradle-proxy.init.gradle.kts dependencies --write-locks spotlessApply --no-daemon
